language: node_js

node_js:
  - "10"

install:
  - travis_wait npm ci
  - lerna bootstrap

script:
  - npm run test-ci

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
