
language: node_js

node_js:
  - "10"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - travis_wait npm ci

script:
  - docker-compose build
  - docker-compose -p tests run -p 3000 --rm todastic npm run test-ci
  - ./travis_integration_test.sh # NOTE: has to run outside the container so that we have a chrome installed

